services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./queries.db
        target: /app/queries.db
    environment:
      - REDDIT_CLIENT_ID=<replaceME>
      - REDDIT_CLIENT_SECRET=<replaceME>
      - TELEGRAM_TOKEN=<replaceME>
      - INTERVAL=300
