services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    build: .
    restart: unless-stopped
    volumes:
      - ./queries.db:/app/queries.db
    environment:
      - REDDIT_CLIENT_ID=<replaceME>
      - REDDIT_CLIENT_SECRET=<replaceME>
      - TELEGRAM_TOKEN=<replaceME>
      - INTERVAL=300
